### ISSUE TITLE
Create strawman slides

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-portal#1]
Example:
- [CollaborationPortal Strawman v2](https://docs.google.com/presentation/d/1_C8kTaQ4Ezh7Tml98cy0VSAmUDxByS0oKGQNkbXuq6s/edit#slide=id.g51ec30945c_0_1)

Add the slides to our ROCC Google folder

**Comment by vpchung** [comment]
First draft of the strawman proposal [here](https://docs.google.com/presentation/d/15haeC-EEYZ_fScaUnXPtFiPzO0ieYn-VRwQKWPNBdDw/edit?usp=sharing).

Let's discuss on Monday!

**Comment by tschaffter** [comment]
This strawman look fabulous! Let's review it together sooner. I sent you a calendar invite.

**Comment by vpchung** [comment]
Next steps:

* play with React boilerplate
* play with Angular boilerplate
