### ISSUE TITLE
Deploy the ROCC API service on a Sage EC2

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-portal#15]
- [x] Create an EC2 in Sage AWS Sandbox
- [x] Clone this repository
- [x] Deploy it using `docker-compose up --build -d`

**Comment by vpchung** [comment]
@tschaffter I created a t3.small instance with the default 8 GB disk space. I think this should be good enough but let me know otherwise.

**Comment by vpchung** [comment]
@tschaffter steps have been completed. Let me know if you would like me to add you as one of the authorized users to the instance!

Otherwise, I think I can close this ticket.
