### ISSUE TITLE
Create Figma project

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-portal#2]
Create a new Figma project based on the project I created for the Challenge Platform.

**Comment by vpchung** [comment]
I think we can close this? Since we have this [Figma project](https://www.figma.com/file/xTj3Lq20tSfKPqPA7Y9lBv/ROCC-Strawman-Edge?node-id=1%3A2) now.

**Comment by tschaffter** [comment]
Done
