### ISSUE TITLE
Identify Personas

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-portal#3]
Identify the stakeholders of the ROCC platform and add them to the Personas sheet of the document [ROCC Use Cases](https://docs.google.com/spreadsheets/d/13KmkKRJzVYig2WgLNdYqS80IQGYBBt5HCd9UsAncDt4/edit#gid=1536110581).

**Comment by tschaffter** [comment]
@vpchung Can you take a pass on this list of personas?

**Comment by vpchung** [comment]
Added a suggestion!

**Comment by vpchung** [comment]
Working draft of persona profiles [here](https://docs.google.com/document/d/1ktmhju14teHIrx9gkwZqPNKeLCzOYXIVjE00ODdv760/edit?usp=sharing).

**Comment by vpchung** [comment]
Starting personas have been identified, so I will close this for now.
