### ISSUE TITLE
Add DB to stack

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-portal#8]
Add a Mongo or SQL DB to the stack. A MongoDB would make prototyping easier as we are working with JSON objects.

**Comment by tschaffter** [comment]
Copy the approach implemented in https://github.com/nlpsandbox/data-node (MongoDB)

**Comment by tschaffter** [comment]
@vpchung As we discussed, this task can be achieve by replicating what I do for the NLP Sandbox Data Node (see above).

**Comment by vpchung** [comment]
#20
